name: K3s-nginx Deployment
on: 
  workflow_dispatch

env:
  AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - uses: actions/checkout@v4

    # Build & test Docker image
    - name: Build Docker image
      run: |
        docker build -t k3s-nginx:latest ./docker

    - name: Test image locally
      run: |
        docker run --rm -p 8080:80 k3s-nginx:latest
        curl -f http://localhost:8080 || exit 1
        docker stop $(docker ps -q)
