name: K3s-nginx Deployment
on: 
  workflow_dispatch

env:
  AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - uses: actions/checkout@v4

    # Build & test Docker image
    - name: Build Docker image
      run: |
        docker build -t k3s-nginx:latest ./docker

    - name: Test image locally
      run: |
        docker run --rm -d --name hello-nginx -p 8080:80 k3s-nginx:latest
        sleep 3
        curl -f http://localhost:8080 || exit 1
        echo "Nginx run successful"
        docker stop hello-nginx
        docker rm -f hello-nginx

    - name: Ansible deploy k3s (shell)
      run: |
        ansible-playbook -i ./ansible/hosts.yaml \
          ./ansible/main.yml \
          --user azureuser \
          -e "ansible_ssh_pass=${{ secrets.AZURE_VM_PASSWORD }}" \
          -e "ansible_become_pass=${{ secrets.AZURE_VM_PASSWORD }}" \
          -e "ansible_ssh_common_args='-o StrictHostKeyChecking=no'" \
          || echo "k3s already installed"    
